config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'sessions/new'

  get 'users/new'

  resources :posts
  get 'static_pages/home'
  get 'static_pages/about', :as => 'about_page'
  root 'static_pages#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :email, presence: true, uniqueness: true
    has_secure_password
    validates :password, presence: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    autho
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    autho
  end

  # POST /posts
  # POST /posts.json
  def create
    autho
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    autho
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    autho
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
    def autho
      unless logged_in?
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.all
  end
  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  config.force_ssl = true
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    autho
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    autho
  end

  # GET /users/new
  def new
    autho
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    autho
  end

  # POST /users
  # POST /users.json
  def create
    autho
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    autho
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    autho
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    def autho
      unless logged_in?
        redirect_to root_url
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Balaram Parajuli</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <table>
      <tr>
        <td><%= link_to 'Home', root_path %></td>
        <td><%= link_to 'Posts', posts_path %></td>
        <td><%= link_to 'About Me', about_page_path %></td>
        <% if logged_in? %>
          <td><%= link_to 'New Post', new_post_path %></td>
          <td><%= link_to current_user.name, current_user %></td>
          <td><%= link_to 'Log out', logout_path %></td>
        <% end %>
      </tr>
    </table>
  </nav>
<%= yield %>
  <footer>
  </footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="wrapper" style="text-align:center">
    <h1>Editing post</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div id="post_index_wrapper" class="wrapper">
  <%# if @post.present? %>
    <h1>Posts</h1>
    <% @posts.each do |post| %>
      <div id="indivisual">
        <div id="title">
          <h1><%= link_to post.title, post %></h1>
        </div>
        <div id="body">
          <p><%= post.body.first(200) %>...<%= link_to "read more", post %></p>
        </div>
        <% if logged_in? %>
          <div id="admin">
            <div class="admin-uses"><%= link_to 'Edit', edit_post_path(post) %></div>
            <div class="admin-uses"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
          </div>
        <% end %>
      </div>
    <%end%>
  <%#else%>
    <!--<h1 style="line-height: 100px;">Sorry, but the author has <br>not uploaded any new posts yet...</h1>-->
  <%# end %>
</div>

app/views/posts/new.html.erb
<div class="wrapper" style="text-align:center;">
  <h1>New post</h1>

  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="wrapper" style="text-align:center;">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @post.body %>
  </p>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/static_pages/about.html.erb
<div id="about_container" class="wrapper" style="text-align:center">
    <% post = Post.find_by(id:1) %>
    <h1><%= post.title %></h1>
    <p><%= post.body %></p>
        <% if logged_in? %>
          <div id="admin">
            <div class="admin-uses"><%= link_to 'Edit', edit_post_path(post) %></div>
            <div class="admin-uses"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
          </div>
        <% end %>
</div>

app/views/static_pages/home.html.erb
<div id="home_container" class = "wrapper">
  <div id="home_header" class="header">
    <div id="date">
      <script>
        document.getElementById("date").innerHTML = Date();
      </script>
    </div>
    <%= image_tag("cubes.jpg")%>
    <h1>Balaram Parajuli</h1>
  </div>
  <div id="top_left">
    <div class="header section_header">
      <%= link_to 'Recent Posts', Post %>
    </div>
    <% @posts.last(3).each do |post| %>
      <div id="indivisual">
        <div id="title">
          <h1><%= link_to post.title, post %></h1>
        </div>
        <div id="body">
          <p><%= post.body.first(200) %>...<%= link_to "read more", post %></p>
          <span title=<%= post.updated_at.localtime.asctime.split.join('-') %>>
           Last Updated: <%= distance_of_time_in_words_to_now(post.updated_at) %> ago
          </span>
        </div>
      </div>
    <%end%>
  </div>
  <div id="top_right">
    <div class="header section_header">
      Slide Show
    </div>
    <div id="home_slide_show">

    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="wrapper">
    <h1>Editing user</h1>
    
    <%= render 'form' %>
    
    <%= link_to 'Show', @user %> |
    <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="wrapper" style="text-align:center;">
<h1>Listing users</h1>

<table style="margin:auto;">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="wrapper" style="text-align:center;">
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="wrapper" style="text-align:center;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  *********************
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
</div>